#!/bin/bash
# ── George: Remote Inference Tunnel ────────────────────────────
# SSH tunnel management for remote GPU inference servers.
# Forwards Ollama (11434) and llama-server (8080) ports from a remote
# VM to localhost, transparent to all HTTP-calling code in llm.sh.
#
# Usage:
#   source lib/remote.sh
#   remote_connect "dabe@george-home"    # opens SSH tunnel
#   remote_tunnel_status                  # check tunnel health
#   remote_disconnect                     # tears down tunnel
#   remote_setup_ssh "dabe@george-home"   # interactive key setup

[ -n "${_LIB_REMOTE_LOADED:-}" ] && return 0; _LIB_REMOTE_LOADED=1

LODGE_DIR="${LODGE_DIR:-$HOME/blue-lodge}"
GEORGE_DIR="${GEORGE_DIR:-${LODGE_DIR}/.george}"

# ── Config Defaults ────────────────────────────────────────────
REMOTE_SSH_TARGET="${REMOTE_SSH_TARGET:-}"
REMOTE_SSH_PORT="${REMOTE_SSH_PORT:-22}"
REMOTE_SSH_KEY="${REMOTE_SSH_KEY:-$HOME/.ssh/id_ed25519}"
REMOTE_OLLAMA_PORT="${REMOTE_OLLAMA_PORT:-11434}"
REMOTE_LLAMACPP_PORT="${REMOTE_LLAMACPP_PORT:-8080}"
REMOTE_LOCAL_OLLAMA_PORT="${REMOTE_LOCAL_OLLAMA_PORT:-11434}"
REMOTE_LOCAL_LLAMACPP_PORT="${REMOTE_LOCAL_LLAMACPP_PORT:-8080}"
# Forward host: final destination as seen from the SSH target.
# "localhost" when the SSH target IS the GPU server.
# An IP like "192.168.30.10" when tunnelling through a jump host.
REMOTE_FORWARD_HOST="${REMOTE_FORWARD_HOST:-localhost}"
# Remote llama-server configuration (used for model switching via SSH)
REMOTE_LLAMACPP_BIN="${REMOTE_LLAMACPP_BIN:-}"
REMOTE_LLAMACPP_GPU_LAYERS="${REMOTE_LLAMACPP_GPU_LAYERS:-99}"
REMOTE_LLAMACPP_CTX_SIZE="${REMOTE_LLAMACPP_CTX_SIZE:-32768}"
REMOTE_OLLAMA_DATA="${REMOTE_OLLAMA_DATA:-/usr/share/ollama/.ollama}"

# ── Internal State ─────────────────────────────────────────────
_REMOTE_PID_FILE="${GEORGE_DIR}/remote-tunnel.pid"
_REMOTE_WATCHDOG_PID_FILE="${GEORGE_DIR}/remote-watchdog.pid"
_REMOTE_CONNECTED=0

# ── Load persisted remote config ───────────────────────────────
_remote_load_config() {
    local _cfg="${GEORGE_DIR}/remote.conf"
    [ -f "$_cfg" ] || return 0
    local _key _val
    while IFS='=' read -r _key _val; do
        [[ "$_key" =~ ^[[:space:]]*# ]] && continue
        [[ "$_key" =~ ^[[:space:]]*$ ]] && continue
        _key=$(echo "$_key" | tr -d '[:space:]')
        _val=$(echo "$_val" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        case "$_key" in
            REMOTE_SSH_TARGET|REMOTE_SSH_PORT|REMOTE_SSH_KEY|\
            REMOTE_OLLAMA_PORT|REMOTE_LLAMACPP_PORT|\
            REMOTE_LOCAL_OLLAMA_PORT|REMOTE_LOCAL_LLAMACPP_PORT|\
            REMOTE_FORWARD_HOST|\
            REMOTE_LLAMACPP_BIN|REMOTE_LLAMACPP_GPU_LAYERS|\
            REMOTE_LLAMACPP_CTX_SIZE|REMOTE_OLLAMA_DATA)
                printf -v "$_key" '%s' "$_val"
                ;;
        esac
    done < "$_cfg"
}

# ── Save remote config ────────────────────────────────────────
_remote_save_config() {
    mkdir -p "$GEORGE_DIR"
    cat > "${GEORGE_DIR}/remote.conf" << EOF
# George remote inference config
# Auto-generated by /remote commands
REMOTE_SSH_TARGET=${REMOTE_SSH_TARGET}
REMOTE_SSH_PORT=${REMOTE_SSH_PORT}
REMOTE_SSH_KEY=${REMOTE_SSH_KEY}
REMOTE_OLLAMA_PORT=${REMOTE_OLLAMA_PORT}
REMOTE_LLAMACPP_PORT=${REMOTE_LLAMACPP_PORT}
REMOTE_LOCAL_OLLAMA_PORT=${REMOTE_LOCAL_OLLAMA_PORT}
REMOTE_LOCAL_LLAMACPP_PORT=${REMOTE_LOCAL_LLAMACPP_PORT}
REMOTE_FORWARD_HOST=${REMOTE_FORWARD_HOST}
REMOTE_LLAMACPP_BIN=${REMOTE_LLAMACPP_BIN}
REMOTE_LLAMACPP_GPU_LAYERS=${REMOTE_LLAMACPP_GPU_LAYERS}
REMOTE_LLAMACPP_CTX_SIZE=${REMOTE_LLAMACPP_CTX_SIZE}
REMOTE_OLLAMA_DATA=${REMOTE_OLLAMA_DATA}
EOF
    chmod 600 "${GEORGE_DIR}/remote.conf"
}

# ── Load on source ─────────────────────────────────────────────
_remote_load_config

# ── Find tunnel PID using multiple methods ─────────────────────
# pgrep often fails in proot (no /proc).  Try multiple approaches.
_remote_find_tunnel_pid() {
    local _target="$1"
    local _pid

    # Method 1: pgrep (works on full Linux, may fail in proot)
    _pid=$(pgrep -n -f "ssh.*-N.*${_target}" 2>/dev/null)
    [ -n "$_pid" ] && { echo "$_pid"; return 0; }

    # Method 2: ps + grep (proot-compatible)
    _pid=$(ps aux 2>/dev/null | grep "ssh.*-N.*${_target}" | grep -v grep | awk '{print $2}' | tail -1)
    [ -n "$_pid" ] && { echo "$_pid"; return 0; }

    # Method 3: ps -ef fallback (busybox/Alpine)
    _pid=$(ps -ef 2>/dev/null | grep "ssh.*-N.*${_target}" | grep -v grep | awk '{print $2}' | tail -1)
    [ -n "$_pid" ] && { echo "$_pid"; return 0; }

    # Method 4: for autossh, find the autossh parent process
    _pid=$(pgrep -n -f "autossh.*${_target}" 2>/dev/null)
    [ -n "$_pid" ] && { echo "$_pid"; return 0; }
    _pid=$(ps aux 2>/dev/null | grep "autossh.*${_target}" | grep -v grep | awk '{print $2}' | tail -1)
    [ -n "$_pid" ] && { echo "$_pid"; return 0; }

    return 1
}

# ── Check if SSH tunnel PID is alive ───────────────────────────
_remote_tunnel_alive() {
    [ -f "$_REMOTE_PID_FILE" ] || return 1
    local _pid
    _pid=$(cat "$_REMOTE_PID_FILE" 2>/dev/null)
    [ -n "$_pid" ] || return 1

    # Try kill -0 first (standard)
    kill -0 "$_pid" 2>/dev/null && return 0

    # Fallback: check /proc (may work even when kill -0 doesn't in proot)
    [ -d "/proc/$_pid" ] 2>/dev/null && return 0

    # Fallback: ps check
    ps -p "$_pid" >/dev/null 2>&1 && return 0

    return 1
}

# ── Ensure ssh-agent is running and key is loaded ─────────────
# Returns 0 if agent is available and key loaded (or key has no passphrase).
# Returns 1 if a passphrase-protected key can't be unlocked (no agent).
_remote_ensure_agent() {
    [ ! -f "$REMOTE_SSH_KEY" ] && return 0

    # If the key has no passphrase, no agent needed
    ssh-keygen -y -P "" -f "$REMOTE_SSH_KEY" &>/dev/null && return 0

    # Key is passphrase-protected — we need an agent
    if [ -z "${SSH_AUTH_SOCK:-}" ]; then
        # Start a new agent
        eval "$(ssh-agent -s)" >/dev/null 2>&1
    fi

    # Check if key is already loaded
    ssh-add -l 2>/dev/null | grep -q "$(ssh-keygen -lf "$REMOTE_SSH_KEY" 2>/dev/null | awk '{print $2}')" 2>/dev/null && return 0

    # Prompt user to unlock
    echo "SSH key is passphrase-protected. Unlocking..." >&2
    ssh-add "$REMOTE_SSH_KEY"
}

# ── Detect and resolve local port conflicts ───────────────────
# If local Ollama (or another process) is already bound to the tunnel's
# local ports, the SSH -L bind will fail.  Auto-remap to offset ports.
_remote_check_port_conflicts() {
    local _ollama_port="${REMOTE_LOCAL_OLLAMA_PORT:-11434}"
    local _llama_port="${REMOTE_LOCAL_LLAMACPP_PORT:-8080}"
    local _remapped=0

    # Check Ollama port
    if _remote_port_in_use "$_ollama_port"; then
        local _new_port=$(( _ollama_port + 10000 ))
        echo "Port $_ollama_port in use (local Ollama?). Remapping tunnel to $_new_port." >&2
        REMOTE_LOCAL_OLLAMA_PORT="$_new_port"
        _remapped=1
    fi

    # Check llama-server port
    if _remote_port_in_use "$_llama_port"; then
        local _new_port=$(( _llama_port + 10000 ))
        echo "Port $_llama_port in use. Remapping tunnel to $_new_port." >&2
        REMOTE_LOCAL_LLAMACPP_PORT="$_new_port"
        _remapped=1
    fi

    if [ "$_remapped" -eq 1 ]; then
        _remote_save_config
    fi
}

# Check if a TCP port is in use (bound by any process).
# Tries multiple methods for proot/Termux compatibility.
_remote_port_in_use() {
    local _port="$1"
    # Method 1: ss (fast, but needs /proc/net — fails in proot)
    if command -v ss >/dev/null 2>&1; then
        ss -tlnH "sport = :$_port" 2>/dev/null | grep -q "$_port" && return 0
    fi
    # Method 2: netstat (may not be installed)
    if command -v netstat >/dev/null 2>&1; then
        netstat -tln 2>/dev/null | grep -q ":$_port " && return 0
    fi
    # Method 3: curl probe (most reliable in proot/Termux)
    if command -v curl >/dev/null 2>&1; then
        curl -sf --max-time 1 "http://127.0.0.1:$_port/" >/dev/null 2>&1 && return 0
    fi
    # Method 4: /dev/tcp (bash built-in, not available everywhere)
    (echo >/dev/tcp/127.0.0.1/"$_port") 2>/dev/null && return 0
    return 1
}

# ── Build SSH args (shared by connect + watchdog) ─────────────
_remote_ssh_base_args() {
    local _fwd_host="${REMOTE_FORWARD_HOST:-localhost}"
    _REMOTE_SSH_ARGS=(-N -o BatchMode=yes -o ConnectTimeout=10
                      -o ServerAliveInterval=30 -o ServerAliveCountMax=3
                      -o ExitOnForwardFailure=yes)
    _REMOTE_SSH_ARGS+=(-p "$REMOTE_SSH_PORT")
    [ -f "$REMOTE_SSH_KEY" ] && _REMOTE_SSH_ARGS+=(-i "$REMOTE_SSH_KEY")
    _REMOTE_SSH_ARGS+=(-L "${REMOTE_LOCAL_OLLAMA_PORT}:${_fwd_host}:${REMOTE_OLLAMA_PORT}")
    _REMOTE_SSH_ARGS+=(-L "${REMOTE_LOCAL_LLAMACPP_PORT}:${_fwd_host}:${REMOTE_LLAMACPP_PORT}")
}

# ── Watchdog: respawn SSH tunnel on failure ────────────────────
# Runs as a background loop.  Killed by remote_disconnect().
_remote_watchdog() {
    local _target="$1"
    while true; do
        # If tunnel process died, reopen it
        if ! _remote_tunnel_alive; then
            _remote_ssh_base_args
            ssh -f "${_REMOTE_SSH_ARGS[@]}" "$_target" 2>/dev/null
            sleep 1
            local _pid
            _pid=$(_remote_find_tunnel_pid "$_target")
            [ -n "$_pid" ] && echo "$_pid" > "$_REMOTE_PID_FILE"
        fi
        sleep 15
    done
}

# ── Execute a command on the remote node via SSH ───────────────
# Usage: _remote_exec "command string"
# Returns the command's exit code, stdout goes to stdout.
# Requires an active tunnel (REMOTE_SSH_TARGET set + key available).
_remote_exec() {
    local _cmd="$1"
    [ -z "$REMOTE_SSH_TARGET" ] && return 1
    ssh -o BatchMode=yes -o ConnectTimeout=10 \
        -p "${REMOTE_SSH_PORT:-22}" \
        -i "$REMOTE_SSH_KEY" \
        "$REMOTE_SSH_TARGET" "$_cmd"
}

# ── Auto-detect remote llama-server binary path ───────────────
# Probes common locations on the remote node.
_remote_detect_llamacpp_bin() {
    [ -n "$REMOTE_LLAMACPP_BIN" ] && return 0
    local _bin
    _bin=$(_remote_exec "command -v llama-server 2>/dev/null || \
        for p in \$HOME/llama.cpp/build/bin/llama-server /usr/local/bin/llama-server /opt/llama.cpp/build/bin/llama-server; do \
            [ -x \"\$p\" ] && echo \"\$p\" && break; \
        done" 2>/dev/null)
    if [ -n "$_bin" ]; then
        REMOTE_LLAMACPP_BIN="$_bin"
        _remote_save_config
        return 0
    fi
    return 1
}

# ── Resolve GGUF blob path on the remote via Ollama manifest ──
# Ollama stores models as blobs referenced by sha256 digests in
# manifests. This queries the remote Ollama's show API (through
# the tunnel) to find the actual GGUF file path on disk.
# Args: $1 — model base name (Ollama tag, e.g. "granite4:3b" or HF ref)
# Returns: absolute path to GGUF file on the remote, or empty.
_remote_resolve_gguf() {
    local _model_ref="$1"
    local _ollama_data="${REMOTE_OLLAMA_DATA:-/usr/share/ollama/.ollama}"

    # Strategy 1: Use Ollama show API (through tunnel) to get the digest,
    # then map to the blob path on the remote filesystem.
    local _show_resp
    _show_resp=$(curl -sf --max-time 10 "$OLLAMA_URL/api/show" \
        -d "{\"name\":\"$_model_ref\"}" 2>/dev/null)
    if [ -n "$_show_resp" ]; then
        local _digest
        _digest=$(echo "$_show_resp" | jq -r \
            '.details.digest // .modelinfo["general.file_type"] // empty' 2>/dev/null)
        # The modelfile FROM line contains the blob reference
        local _from_blob
        _from_blob=$(echo "$_show_resp" | jq -r '.modelfile // ""' 2>/dev/null \
            | grep -oP '(?<=FROM\s)/\S+' | head -1)
        if [ -n "$_from_blob" ]; then
            echo "$_from_blob"
            return 0
        fi
    fi

    # Strategy 2: SSH and find the GGUF by searching Ollama's blob store
    # for the model's manifest → extract the layer digest → resolve blob path.
    local _gguf_path
    _gguf_path=$(_remote_exec "
        _data='${_ollama_data}'
        # Try to find the manifest for the model
        _ref='${_model_ref}'
        # Normalize: 'hf.co/...' → search for the tag in manifests
        for _manifest in \$(find \"\$_data/models/manifests\" -name '*' -type f 2>/dev/null | head -20); do
            _layer=\$(jq -r '.layers[] | select(.mediaType | test(\"model\")) | .digest' \"\$_manifest\" 2>/dev/null | head -1)
            if [ -n \"\$_layer\" ]; then
                _blob=\"\$_data/models/blobs/\$(echo \"\$_layer\" | tr ':' '-')\"
                if [ -f \"\$_blob\" ]; then
                    echo \"\$_blob\"
                    exit 0
                fi
            fi
        done
        # Strategy 3: Find by partial name match in blob filenames
        _match=\$(find \"\$_data/models/blobs\" -type f -name 'sha256-*' -size +500M 2>/dev/null | head -1)
        [ -n \"\$_match\" ] && echo \"\$_match\"
    " 2>/dev/null)

    [ -n "$_gguf_path" ] && echo "$_gguf_path"
}

# ── Restart llama-server on the remote node with a new model ──
# Kills the existing llama-server and starts it with the new GGUF.
# Args: $1 — model name/key from the registry
# Returns 0 on success (remote server healthy), 1 on failure.
_remote_restart_llamacpp() {
    local _model_name="$1"
    local _model_base="$2"  # Ollama tag or HF ref from registry

    [ -z "$REMOTE_SSH_TARGET" ] && {
        echo "ERROR: No remote SSH target configured" >&2
        return 1
    }

    # Auto-detect remote llama-server binary if not configured
    if [ -z "$REMOTE_LLAMACPP_BIN" ]; then
        _remote_detect_llamacpp_bin || {
            echo "ERROR: Cannot find llama-server on remote. Set REMOTE_LLAMACPP_BIN in /remote config." >&2
            return 1
        }
    fi

    # Resolve GGUF path on remote
    local _remote_gguf=""

    # First try: resolve via Ollama API (model is pulled on remote)
    if [ -n "$_model_base" ]; then
        _remote_gguf=$(_remote_resolve_gguf "$_model_base")
    fi

    # Fallback: ask the remote to find it via Ollama show CLI
    if [ -z "$_remote_gguf" ] && [ -n "$_model_base" ]; then
        _remote_gguf=$(_remote_exec "ollama show --modelfile '$_model_base' 2>/dev/null | grep -oP '(?<=FROM\s)/\S+' | head -1" 2>/dev/null)
    fi

    if [ -z "$_remote_gguf" ]; then
        echo "ERROR: Cannot resolve GGUF for '$_model_name' on remote" >&2
        echo "  Ensure the model is pulled on the remote: /remote pull $_model_base" >&2
        return 1
    fi

    local _port="${REMOTE_LLAMACPP_PORT:-8080}"
    local _ngl="${REMOTE_LLAMACPP_GPU_LAYERS:-99}"
    local _ctx="${REMOTE_LLAMACPP_CTX_SIZE:-32768}"
    local _bin="$REMOTE_LLAMACPP_BIN"

    # Determine chat template args based on model
    local _extra_args=""
    # Qwen 3.5 models need --chat-template-kwargs for thinking mode
    if [[ "$_model_name" =~ qwen35.*think ]]; then
        _extra_args="--chat-template-kwargs '{\"enable_thinking\":true}'"
    fi

    # Kill existing llama-server and start new one on the remote
    local _restart_result
    _restart_result=$(_remote_exec "
        # Kill existing llama-server
        _pid=\$(pgrep -f 'llama-server.*--port' 2>/dev/null | head -1)
        if [ -n \"\$_pid\" ]; then
            kill \"\$_pid\" 2>/dev/null
            sleep 2
            kill -9 \"\$_pid\" 2>/dev/null
            wait \"\$_pid\" 2>/dev/null
        fi
        sleep 1
        # Start new llama-server in background
        nohup $_bin -m '$_remote_gguf' \\
            --port $_port --host 0.0.0.0 \\
            --jinja -ngl $_ngl -c $_ctx \\
            --threads \$(nproc 2>/dev/null || echo 4) \\
            --parallel 1 $_extra_args \\
            > /tmp/llama-server.log 2>&1 &
        echo \$!
    " 2>/dev/null)

    if [ -z "$_restart_result" ]; then
        echo "ERROR: Failed to restart llama-server on remote" >&2
        return 1
    fi

    # Wait for healthy status (model loading can take 10-30s on GPU)
    local _wait=0
    local _max_wait=60
    while [ "$_wait" -lt "$_max_wait" ]; do
        sleep 2
        _wait=$((_wait + 2))
        local _health
        _health=$(curl -sf --max-time 3 "$LLAMA_CPP_URL/health" 2>/dev/null)
        if echo "$_health" | grep -q '"ok"' 2>/dev/null; then
            return 0
        fi
        # Still loading — keep waiting
        if echo "$_health" | grep -q '"loading"' 2>/dev/null; then
            continue
        fi
    done

    echo "WARNING: Remote llama-server started (PID $_restart_result) but not healthy after ${_max_wait}s" >&2
    return 1
}

# ── Connect: open SSH tunnel ───────────────────────────────────
# Usage: remote_connect [user@host]
# Prefers autossh when available; falls back to ssh + bash watchdog.
remote_connect() {
    local target="${1:-$REMOTE_SSH_TARGET}"

    if [ -z "$target" ]; then
        echo "ERROR: No SSH target. Use: remote_connect user@host" >&2
        echo "  Or set REMOTE_SSH_TARGET and run /remote connect" >&2
        return 1
    fi

    # Kill existing tunnel if any
    if _remote_tunnel_alive; then
        remote_disconnect 2>/dev/null
    fi

    # Unlock passphrase-protected key via ssh-agent if needed
    _remote_ensure_agent || {
        echo "ERROR: Cannot unlock SSH key. Run /remote secure to manage key passphrase." >&2
        return 1
    }

    # Detect local port conflicts (e.g., local Ollama already on 11434)
    _remote_check_port_conflicts

    _remote_ssh_base_args
    local _fwd_host="${REMOTE_FORWARD_HOST:-localhost}"
    local _method="ssh"

    if command -v autossh >/dev/null 2>&1; then
        # autossh: handles reconnection natively.
        # AUTOSSH_GATETIME=0 lets it survive fast first-connect failures.
        # -M 0 disables autossh's own monitoring; we rely on ServerAlive.
        local _ssh_err
        _ssh_err=$(mktemp "${TMPDIR:-/tmp}/remote-ssh-err.XXXXXX")
        AUTOSSH_GATETIME=0 autossh -M 0 -f "${_REMOTE_SSH_ARGS[@]}" "$target" 2>"$_ssh_err"
        _method="autossh"
    else
        # Plain ssh with -f (backgrounds after auth)
        local _ssh_err
        _ssh_err=$(mktemp "${TMPDIR:-/tmp}/remote-ssh-err.XXXXXX")
        ssh -f "${_REMOTE_SSH_ARGS[@]}" "$target" 2>"$_ssh_err"
    fi
    local rc=$?

    if [ $rc -ne 0 ]; then
        echo "ERROR: SSH tunnel failed (exit $rc). Check:" >&2
        echo "  - SSH key: $REMOTE_SSH_KEY" >&2
        echo "  - Target: $target:$REMOTE_SSH_PORT" >&2
        echo "  - Forward host: $_fwd_host" >&2
        [ -f "$_ssh_err" ] && [ -s "$_ssh_err" ] && echo "  - SSH error: $(cat "$_ssh_err")" >&2
        echo "  - Run /remote setup to configure SSH keys" >&2
        rm -f "$_ssh_err" 2>/dev/null
        return 1
    fi

    # Find the SSH tunnel PID.
    # autossh -f backgrounds; give it a moment to spawn the ssh child.
    sleep 2
    local _pid
    _pid=$(_remote_find_tunnel_pid "$target")
    if [ -n "$_pid" ]; then
        mkdir -p "$GEORGE_DIR"
        echo "$_pid" > "$_REMOTE_PID_FILE"
    fi

    # Start bash watchdog when autossh is not available
    if [ "$_method" = "ssh" ]; then
        _remote_watchdog "$target" &
        echo "$!" > "$_REMOTE_WATCHDOG_PID_FILE"
    fi

    # Save target for reconnection
    REMOTE_SSH_TARGET="$target"
    _remote_save_config

    # Update URLs to point through tunnel
    OLLAMA_URL="http://127.0.0.1:${REMOTE_LOCAL_OLLAMA_PORT}"
    LLAMA_CPP_URL="http://127.0.0.1:${REMOTE_LOCAL_LLAMACPP_PORT}"

    _REMOTE_CONNECTED=1
    echo "Connected to $target (via $_method)"
    [ "$_fwd_host" != "localhost" ] && echo "  Forward host: $_fwd_host"
    echo "  Ollama:       $OLLAMA_URL"
    echo "  llama-server: $LLAMA_CPP_URL"

    # Post-connect health check: verify tunnel is actually forwarding
    local _tunnel_ok=0
    if curl -sf --max-time 3 "$OLLAMA_URL/api/tags" &>/dev/null; then
        _tunnel_ok=1
    elif curl -sf --max-time 3 "$LLAMA_CPP_URL/health" &>/dev/null; then
        _tunnel_ok=1
    fi

    if [ "$_tunnel_ok" -eq 0 ]; then
        echo "" >&2
        echo "WARNING: Tunnel process is running but remote endpoints are not responding." >&2
        echo "  This usually means the SSH connection authenticated but port" >&2
        echo "  forwarding isn't reaching the remote services." >&2
        echo "" >&2
        echo "  Diagnostics:" >&2
        [ -f "$_ssh_err" ] && [ -s "$_ssh_err" ] && echo "  SSH stderr: $(cat "$_ssh_err")" >&2
        echo "  Try: /remote diagnose" >&2
        echo "  Or manually: ssh -v -N -L ${REMOTE_LOCAL_OLLAMA_PORT}:${_fwd_host}:${REMOTE_OLLAMA_PORT} $target" >&2
    fi

    rm -f "$_ssh_err" 2>/dev/null
    return 0
}

# ── Disconnect: tear down SSH tunnel ───────────────────────────
remote_disconnect() {
    # Kill watchdog first so it doesn't respawn the tunnel
    if [ -f "$_REMOTE_WATCHDOG_PID_FILE" ]; then
        local _wpid
        _wpid=$(cat "$_REMOTE_WATCHDOG_PID_FILE" 2>/dev/null)
        if [ -n "$_wpid" ]; then
            kill "$_wpid" 2>/dev/null
            wait "$_wpid" 2>/dev/null
        fi
        rm -f "$_REMOTE_WATCHDOG_PID_FILE"
    fi

    if [ -f "$_REMOTE_PID_FILE" ]; then
        local _pid
        _pid=$(cat "$_REMOTE_PID_FILE" 2>/dev/null)
        if [ -n "$_pid" ]; then
            kill "$_pid" 2>/dev/null
            # Wait briefly for clean exit
            local _i=0
            while kill -0 "$_pid" 2>/dev/null && [ $_i -lt 10 ]; do
                sleep 0.1
                _i=$((_i + 1))
            done
        fi
        rm -f "$_REMOTE_PID_FILE"
    fi

    # Also kill any lingering autossh if it was used
    if [ -n "$REMOTE_SSH_TARGET" ]; then
        pkill -f "autossh.*${REMOTE_SSH_TARGET}" 2>/dev/null
    fi

    _REMOTE_CONNECTED=0

    # Restore default localhost URLs and reset remapped ports
    REMOTE_LOCAL_OLLAMA_PORT="11434"
    REMOTE_LOCAL_LLAMACPP_PORT="8080"
    OLLAMA_URL="http://127.0.0.1:11434"
    LLAMA_CPP_URL="http://127.0.0.1:8080"
    _remote_save_config

    echo "Disconnected. URLs restored to localhost defaults."
    return 0
}

# ── Status: check tunnel health + probe endpoints ─────────────
# Returns 0 if tunnel alive and at least one endpoint reachable.
remote_tunnel_status() {
    local _status="disconnected"
    local _pid="none"
    local _target="${REMOTE_SSH_TARGET:-<not set>}"
    local _ollama_status="unreachable"
    local _llamacpp_status="unreachable"

    if _remote_tunnel_alive; then
        _pid=$(cat "$_REMOTE_PID_FILE" 2>/dev/null)
        _status="connected"

        # Probe Ollama
        if curl -sf --max-time 2 "http://127.0.0.1:${REMOTE_LOCAL_OLLAMA_PORT}/api/tags" &>/dev/null; then
            _ollama_status="running"
        fi

        # Probe llama-server
        local _health
        _health=$(curl -sf --max-time 2 "http://127.0.0.1:${REMOTE_LOCAL_LLAMACPP_PORT}/health" 2>/dev/null)
        if [ $? -eq 0 ]; then
            _llamacpp_status=$(echo "$_health" | jq -r '.status // "unknown"' 2>/dev/null)
            [ -z "$_llamacpp_status" ] && _llamacpp_status="running"
        fi
    elif [ -f "$_REMOTE_PID_FILE" ]; then
        _status="stale (tunnel died)"
        rm -f "$_REMOTE_PID_FILE"
    fi

    local _fwd="${REMOTE_FORWARD_HOST:-localhost}"
    local _method="ssh"
    command -v autossh >/dev/null 2>&1 && _method="autossh"
    [ -f "$_REMOTE_WATCHDOG_PID_FILE" ] && kill -0 "$(cat "$_REMOTE_WATCHDOG_PID_FILE" 2>/dev/null)" 2>/dev/null && _method="ssh+watchdog"

    printf "  %-22s %s\n" "Status:" "$_status"
    printf "  %-22s %s\n" "Target:" "$_target"
    printf "  %-22s %s\n" "Forward host:" "$_fwd"
    printf "  %-22s %s\n" "Tunnel PID:" "$_pid"
    printf "  %-22s %s\n" "Method:" "$_method"
    printf "  %-22s %s\n" "Ollama:" "$_ollama_status (port ${REMOTE_LOCAL_OLLAMA_PORT})"
    printf "  %-22s %s\n" "llama-server:" "$_llamacpp_status (port ${REMOTE_LOCAL_LLAMACPP_PORT})"

    [ "$_status" = "connected" ] && return 0
    return 1
}

# ── Setup: interactive SSH key configuration ───────────────────
# Usage: remote_setup_ssh [user@host]
remote_setup_ssh() {
    local target="${1:-}"

    if [ -z "$target" ]; then
        echo "Usage: /remote setup user@host"
        echo "  Generates SSH key (if needed) and copies to remote host."
        return 1
    fi

    # Check dependencies
    if ! command -v ssh-keygen >/dev/null 2>&1; then
        echo "ERROR: ssh-keygen not found. Install openssh-client." >&2
        return 1
    fi

    # Generate key if it doesn't exist
    if [ ! -f "$REMOTE_SSH_KEY" ]; then
        echo "Generating SSH key: $REMOTE_SSH_KEY"
        ssh-keygen -t ed25519 -f "$REMOTE_SSH_KEY" -N "" -C "george@$(hostname)"
        if [ $? -ne 0 ]; then
            echo "ERROR: Key generation failed." >&2
            return 1
        fi
        echo "Key generated."
    else
        echo "SSH key exists: $REMOTE_SSH_KEY"
    fi

    # Test if key is already authorized on remote
    echo "Testing existing key..."
    if ssh -o BatchMode=yes -o ConnectTimeout=5 -p "$REMOTE_SSH_PORT" -i "$REMOTE_SSH_KEY" "$target" "echo ok" &>/dev/null; then
        echo "SSH key already authorized on $target."
        REMOTE_SSH_TARGET="$target"
        _remote_save_config
        echo "Saved target: $target"
        echo ""
        echo "Next: /remote connect"
        return 0
    fi

    # Key not yet authorized — copy it to remote
    if command -v ssh-copy-id >/dev/null 2>&1; then
        echo "Copying key to $target..."
        ssh-copy-id -i "$REMOTE_SSH_KEY" -p "$REMOTE_SSH_PORT" "$target"
        local rc=$?
        if [ $rc -ne 0 ]; then
            echo "ERROR: ssh-copy-id failed. You may need to copy manually:" >&2
            echo "  cat ${REMOTE_SSH_KEY}.pub | ssh -p $REMOTE_SSH_PORT $target 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'" >&2
            return 1
        fi
    else
        echo "ssh-copy-id not found. Copy key manually:"
        echo "  cat ${REMOTE_SSH_KEY}.pub | ssh -p $REMOTE_SSH_PORT $target 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'"
        return 1
    fi

    # Test connection
    echo "Testing connection..."
    if ssh -o BatchMode=yes -o ConnectTimeout=5 -p "$REMOTE_SSH_PORT" -i "$REMOTE_SSH_KEY" "$target" "echo ok" &>/dev/null; then
        echo "SSH connection successful."
        REMOTE_SSH_TARGET="$target"
        _remote_save_config
        echo "Saved target: $target"
        echo ""
        echo "Next: /remote connect"
    else
        echo "ERROR: SSH test failed. Check credentials and network." >&2
        return 1
    fi
    return 0
}

# ── Secure key: add/change passphrase + ensure ssh-agent ──────
# Usage: remote_secure_key
remote_secure_key() {
    if [ ! -f "$REMOTE_SSH_KEY" ]; then
        echo "No SSH key found at $REMOTE_SSH_KEY" >&2
        echo "Run /remote setup first to generate one." >&2
        return 1
    fi

    # Check if the key already has a passphrase
    if ssh-keygen -y -P "" -f "$REMOTE_SSH_KEY" &>/dev/null; then
        echo "Adding passphrase to SSH key: $REMOTE_SSH_KEY"
        echo "You will be prompted to set a new passphrase."
        ssh-keygen -p -f "$REMOTE_SSH_KEY"
        local rc=$?
        if [ $rc -ne 0 ]; then
            echo "ERROR: Failed to set passphrase." >&2
            return 1
        fi
        echo "Passphrase set."
    else
        echo "SSH key is already passphrase-protected."
        echo "To change it, you'll need the current passphrase."
        ssh-keygen -p -f "$REMOTE_SSH_KEY"
    fi

    # Start agent and load the key so the current session works
    if [ -z "${SSH_AUTH_SOCK:-}" ]; then
        eval "$(ssh-agent -s)" >/dev/null 2>&1
        echo "Started ssh-agent (PID: $SSH_AGENT_PID)"
    fi
    echo "Loading key into ssh-agent..."
    ssh-add "$REMOTE_SSH_KEY"
    if [ $? -eq 0 ]; then
        echo "Key loaded. You won't be prompted for the passphrase again this session."
        echo ""
        echo "Tip: To persist across terminal sessions, add to your shell profile:"
        echo '  eval "$(ssh-agent -s)" && ssh-add '"$REMOTE_SSH_KEY"
    fi
}

# ── Probe remote endpoints without tunnel (direct URL check) ──
# Used by /remote status when URLs are set manually (no SSH tunnel).
remote_probe_endpoints() {
    local _ollama_url="${OLLAMA_URL:-http://127.0.0.1:11434}"
    local _llamacpp_url="${LLAMA_CPP_URL:-http://127.0.0.1:8080}"
    local _result=""

    # Ollama
    local _tags
    _tags=$(curl -sf --max-time 3 "${_ollama_url}/api/tags" 2>/dev/null)
    if [ $? -eq 0 ] && [ -n "$_tags" ]; then
        local _count
        _count=$(echo "$_tags" | jq '.models | length' 2>/dev/null)
        _result="Ollama: running (${_count:-0} models)"
    else
        _result="Ollama: unreachable"
    fi

    # llama-server
    local _health
    _health=$(curl -sf --max-time 3 "${_llamacpp_url}/health" 2>/dev/null)
    if [ $? -eq 0 ] && [ -n "$_health" ]; then
        local _lstatus
        _lstatus=$(echo "$_health" | jq -r '.status // "unknown"' 2>/dev/null)
        _result="${_result}\nllama-server: ${_lstatus}"
    else
        _result="${_result}\nllama-server: unreachable"
    fi

    echo -e "$_result"
}

# ── Diagnose: verbose connectivity check ───────────────────────
# Runs through each layer of the tunnel to pinpoint failures.
remote_diagnose() {
    local target="${REMOTE_SSH_TARGET:-}"
    local _fwd="${REMOTE_FORWARD_HOST:-localhost}"
    local _ollama_port="${REMOTE_LOCAL_OLLAMA_PORT:-11434}"
    local _llamacpp_port="${REMOTE_LOCAL_LLAMACPP_PORT:-8080}"
    local _remote_ollama="${REMOTE_OLLAMA_PORT:-11434}"
    local _remote_llamacpp="${REMOTE_LLAMACPP_PORT:-8080}"

    echo "=== Remote Inference Diagnostics ==="
    echo ""

    # 1. Config
    echo "── Configuration ──"
    printf "  %-22s %s\n" "SSH target:" "${target:-<not set>}"
    printf "  %-22s %s\n" "SSH port:" "${REMOTE_SSH_PORT:-22}"
    printf "  %-22s %s\n" "SSH key:" "$REMOTE_SSH_KEY"
    printf "  %-22s %s\n" "Forward host:" "$_fwd"
    printf "  %-22s %s\n" "Local Ollama port:" "$_ollama_port"
    printf "  %-22s %s\n" "Local llama port:" "$_llamacpp_port"
    printf "  %-22s %s\n" "Remote Ollama port:" "$_remote_ollama"
    printf "  %-22s %s\n" "Remote llama port:" "$_remote_llamacpp"
    echo ""

    # 2. SSH key exists?
    echo "── SSH Key ──"
    if [ -f "$REMOTE_SSH_KEY" ]; then
        echo "  Key exists: $REMOTE_SSH_KEY"
        local _fp
        _fp=$(ssh-keygen -lf "$REMOTE_SSH_KEY" 2>/dev/null)
        [ -n "$_fp" ] && echo "  Fingerprint: $_fp"
    else
        echo "  ERROR: Key not found: $REMOTE_SSH_KEY"
        echo "  Run: /remote setup $target"
        return 1
    fi
    echo ""

    # 3. SSH auth test
    echo "── SSH Authentication ──"
    if [ -z "$target" ]; then
        echo "  SKIP: No target configured. Run /remote setup user@host"
    else
        echo "  Testing: ssh -o BatchMode=yes $target ..."
        local _ssh_out
        _ssh_out=$(ssh -v -o BatchMode=yes -o ConnectTimeout=5 \
            -p "${REMOTE_SSH_PORT:-22}" -i "$REMOTE_SSH_KEY" \
            "$target" "echo __DIAGNOSE_OK__" 2>&1)
        if echo "$_ssh_out" | grep -q "__DIAGNOSE_OK__"; then
            echo "  Auth: OK"
        else
            echo "  Auth: FAILED"
            echo ""
            echo "  Verbose output (last 20 lines):"
            echo "$_ssh_out" | tail -20 | sed 's/^/    /'
            echo ""
            echo "  Fix: Run /remote setup $target to copy your key."
            return 1
        fi
    fi
    echo ""

    # 4. Tunnel process
    echo "── Tunnel Process ──"
    if _remote_tunnel_alive; then
        local _pid
        _pid=$(cat "$_REMOTE_PID_FILE" 2>/dev/null)
        echo "  Tunnel PID: $_pid (alive)"
    else
        echo "  Tunnel: not running"
    fi
    # Show all SSH/autossh processes
    echo "  SSH processes:"
    ps aux 2>/dev/null | grep -E '[s]sh|[a]utossh' | grep -v grep | sed 's/^/    /' || \
        ps -ef 2>/dev/null | grep -E '[s]sh|[a]utossh' | grep -v grep | sed 's/^/    /' || \
        echo "    (cannot list processes)"
    echo ""

    # 5. Local port listeners
    echo "── Local Ports ──"
    for _p in "$_ollama_port" "$_llamacpp_port"; do
        local _listening="unknown"
        if command -v ss >/dev/null 2>&1; then
            ss -tlnp 2>/dev/null | grep -q ":${_p} " && _listening="listening" || _listening="not listening"
        elif command -v netstat >/dev/null 2>&1; then
            netstat -tlnp 2>/dev/null | grep -q ":${_p} " && _listening="listening" || _listening="not listening"
        else
            # Curl probe
            if curl -sf --max-time 1 "http://127.0.0.1:${_p}/" &>/dev/null; then
                _listening="responding"
            else
                _listening="not responding (curl probe)"
            fi
        fi
        printf "  Port %-6s %s\n" "$_p:" "$_listening"
    done
    echo ""

    # 6. Endpoint health
    echo "── Endpoint Probes ──"
    echo "  Ollama (http://127.0.0.1:${_ollama_port}/api/tags):"
    local _o_resp
    _o_resp=$(curl -sf --max-time 3 "http://127.0.0.1:${_ollama_port}/api/tags" 2>&1)
    if [ $? -eq 0 ] && [ -n "$_o_resp" ]; then
        local _count
        _count=$(echo "$_o_resp" | jq '.models | length' 2>/dev/null)
        echo "    OK — ${_count:-0} models available"
    else
        echo "    UNREACHABLE"
    fi

    echo "  llama-server (http://127.0.0.1:${_llamacpp_port}/health):"
    local _l_resp
    _l_resp=$(curl -sf --max-time 3 "http://127.0.0.1:${_llamacpp_port}/health" 2>&1)
    if [ $? -eq 0 ] && [ -n "$_l_resp" ]; then
        echo "    OK — $(echo "$_l_resp" | jq -r '.status // "unknown"' 2>/dev/null)"
    else
        echo "    UNREACHABLE"
    fi
    echo ""

    # 7. Quick tunnel test (if target set, try a one-shot forwarded connection)
    if [ -n "$target" ] && ! _remote_tunnel_alive; then
        echo "── Quick Tunnel Test ──"
        echo "  Attempting brief SSH tunnel to test forwarding..."
        local _test_out
        _test_out=$(ssh -v -o BatchMode=yes -o ConnectTimeout=5 \
            -o ExitOnForwardFailure=yes \
            -p "${REMOTE_SSH_PORT:-22}" -i "$REMOTE_SSH_KEY" \
            -L "${_ollama_port}:${_fwd}:${_remote_ollama}" \
            -N "$target" 2>&1 &)
        local _test_pid=$!
        sleep 3
        if curl -sf --max-time 2 "http://127.0.0.1:${_ollama_port}/api/tags" &>/dev/null; then
            echo "  Tunnel forwarding: OK"
        else
            echo "  Tunnel forwarding: FAILED"
            echo "  This means SSH connects but port forwarding isn't reaching the remote service."
            echo "  Check that the forward host ($_fwd) is correct and services are running on the remote."
        fi
        kill "$_test_pid" 2>/dev/null
        wait "$_test_pid" 2>/dev/null
    fi

    echo "=== End Diagnostics ==="
    return 0
}
